DTYPES = {
    'game_pk':                                  'int64',
    'pitch_number':                             'int64',
    'at_bat_number':                            'int64',
    'game_date':                                'datetime',
    'pitcher_id':                               'int64',
    'batter_id':                                'int64',
    'pitcher':                                  'int64', 
    'batter':                                   'int64', 
    'on_3b':                                    'int64', 
    'on_2b':                                    'int64',
    'on_1b':                                    'int64',
    'zone':                                     'int64',
    'balls':                                    'int64',
    'strikes':                                  'int64',
    'inning':                                   'int64',
    'outs_when_up':                             'int64',
    'home_score':                               'int64',
    'away_score':                               'int64',
    'bat_score':                                'int64',
    'fld_score':                                'int64',
    'hit_location':                             'int64',
    'is_whiff':                                 'boolean',
    'is_bip':                                   'boolean',
    'is_called_strike':                         'boolean',
    'is_ball':                                  'boolean',
    'is_strikeout':                             'boolean',
    'is_walk':                                  'boolean',
    'pitch_type':                               'string',
    'pitch_name':                               'string',
    'events':                                   'string',
    'description':                              'string',
    'pitch_result_type':                        'string',
    'p_throws':                                 'string',
    'stand':                                    'string',
    'if_fielding_alignment':                    'string',
    'of_fielding_alignment':                    'string',
    'bb_type':                                  'string',
    'release_pos_x':                            'float64',
    'release_pos_y':                            'float64',
    'release_pos_z':                            'float64',
    'release_speed':                            'float64',
    'release_spin_rate':                        'float64',
    'release_extension':                        'float64',
    'spin_axis':                                'float64',
    'effective_speed':                          'float64',
    'pfx_x':                                    'float64',
    'pfx_z':                                    'float64',
    'vx0':                                      'float64',
    'vy0':                                      'float64',
    'vz0':                                      'float64',
    'az':                                       'float64',
    'ax':                                       'float64',
    'ay':                                       'float64',
    'plate_x':                                  'float64',
    'plate_z':                                  'float64',
    'sz_top':                                   'float64',
    'sz_bot':                                   'float64',
    'api_break_z_with_gravity':                 'float64',
    'api_break_x_arm':                          'float64',
    'api_break_x_batter_in':                    'float64',
    'arm_angle':                                'float64',
    'attack_angle':                             'float64',
    'attack_direction':                         'float64',
    'swing_path_tilt':                          'float64',
    'launch_angle':                             'float64'
    }

BOUNDS = {
    'pitch_number':                             (1, 130),
    'at_bat_number':                            (1, 185),
    'balls':                                    (0, 3),
    'strikes':                                  (0, 2),
    'outs_when_up':                             (0, 2),
    'inning':                                   (1, 30),
    'home_score':                               (0, 25),
    'away_score':                               (0, 25),
    'bat_score':                                (0, 25),
    'fld_score':                                (0, 25),
    'home_score_diff':                          (0, 25),
    'bat_score_diff':                           (0, 25),
    'hit_location':                             (1, 9),
    'release_speed':                            (20, 108),
    'release_pos_x':                            (-6, 6),
    'release_pos_y':                            (46, 60),
    'release_pos_z':                            (2.5, 9),
    'release_spin_rate':                        (500, 3500),
    'release_extension':                        (3.5, 9),
    'spin_axis':                                (0, 360),
    'effective_speed':                          (60, 110),
    'pfx_x':                                    (-5, 5),
    'pfx_z':                                    (-4.5, 4.5),
    'vy0':                                      (-180, -50),
    'vx0':                                      (-30, 30),
    'vz0':                                      (-30, 30),
    'ay':                                       (0, 50),
    'ax':                                       (-50, 50),
    'az':                                       (-60, 20),
    'zone':                                     (1, 14),
    'plate_x':                                  (-3, 3),
    'plate_z':                                  (0, 7),
    'attack_angle':                             (-90, 90),
    'attack_direction':                         (-180, 180),
    'swing_path_tilt':                          (0, 90),
    'launch_angle':                             (-90, 90),
    'arm_angle':                                (-30, 90)
}

# COLUMNS TO BE FLAGGED DURING PRODUCTION:
# - sz_top/sz_bot
# - arm_angle/attack_angle
# - 