from sqlalchemy import create_engine, text
from utils.utils import build_db_url

engine = create_engine(build_db_url(), pool_pre_ping=False)

query = """
    CREATE TABLE IF NOT EXISTS raw.statcast_pitching (
        game_date_text                          text,
        pitch_type_text                         text,
        release_speed_text                      text,
        release_pos_x_text                      text,
        release_pos_z_text                      text,
        player_name_text                        text,
        batter_id_text                          text,
        pitcher_id_text                         text,
        events_text                             text,
        description_text                        text,
        spin_dir_text                           text,
        zone_text                               text,
        des_text                                text,
        game_type_text                          text,
        stand_text                              text,
        p_throws_text                           text,
        home_team_text                          text,
        away_team_text                          text,
        type_text                               text,
        hit_location_text                       text,
        bb_text                                 text,
        balls_text                              text,
        strikes_text                            text,
        game_year_text                          text,
        pfx_x_text                              text,
        pfx_z_text                              text,
        plate_x_text                            text,
        plate_z_text                            text,
        on_3b_text                              text,
        on_2b_text                              text,
        on_1b_text                              text,
        outs_when_up_text                       text,
        inning_text                             text,
        inning_topbot_text                      text,
        hc_x_text                               text,
        hc_y_text                               text,
        umpire_text                             text,
        sv_id_text                              text,
        vx0_text                                text,
        vy0_text                                text,
        vz0_text                                text,
        ax_text                                 text,
        ay_text                                 text,
        az_text                                 text,
        sz_top_text                             text,
        sz_bot_text                             text,
        hit_distance_sc_text                    text,
        launch_speed_text                       text,
        launch_angle_text                       text,
        effective_speed_text                    text,
        release_spin_rate_text                  text,
        release_extension_text                  text,
        game_pk_text                            text,
        fielder_2_text                          text,
        fielder_3_text                          text,
        fielder_4_text                          text,
        fielder_5_text                          text,
        fielder_6_text                          text,
        fielder_7_text                          text,
        fielder_8_text                          text,
        fielder_9_text                          text,
        release_pos_y_text                      text,
        estimated_ba_using_speedangle_text      text,
        estimated_woba_using_speedangle_text    text,
        woba_value_text                         text,
        woba_denom_text                         text,
        babip_value_text                        text,
        iso_value_text                          text,
        launch_speed_angle_text                 text,
        at_bat_number_text                      text,
        pitch_number_text                       text,
        pitch_name_text                         text,
        home_score_text                         text,
        away_score_text                         text,
        bat_score_text                          text,
        fld_score_text                          text,
        post_away_score_text                    text,
        post_home_score_text                    text,
        post_bat_score_text                     text,
        post_fld_score_text                     text,
        if_fielding_alignment_text              text,
        of_fielding_alignment_text              text,
        spin_axis_text                          text,
        delta_home_win_exp_text                 text,
        delta_run_exp_text                      text,
        bat_speed_text                          text,
        swing_length_text                       text,
        estimated_slg_using_speedangle_text     text,
        n_priorpa_thisgame_player_at_bat_text   text,
        pitcher_days_since_prev_game_text       text,
        batter_days_since_prev_game_text        text,
        pitcher_days_until_next_game_text       text,
        batter_days_until_next_game_text        text,
        api_break_z_with_gravity_text           text,
        api_break_x_arm_text                    text,
        api_break_x_batter_in_text              text,
        arm_angle_text                          text,
        attack_angle_text                       text,
        attack_direction_text                   text,
        swing_path_tilt_text                    text,
        intercept_ball_minus_batter_pos_x_inches_text       text,
        intercept_ball_minus_batter_pos_y_inches_text       text
    );
"""



def main():
    with engine.begin() as conn:
        conn.execute(text(query))


if __name__ == "__main__":
    main()